url: "https://www.camcoulter.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Cam Coulter" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-toc
  - jekyll-paginate
