SPDX-FileCopyrightText: 2021 Cam Coulter <git@camcoulter.com>
SPDX-License-Identifier: AGPL-3.0-or-later

url: "https://www.camcoulter.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Cam Coulter"
author: "Cam Coulter"
timezone: America/Los_Angeles
permalink: /:year/:month/:day/:title/
default_image: desk-keyboard-notebook
default_description: "Cam Coulter is a writer and accessibility nerd, among other things. They work as a training specialist for a disability services organization, and they think incessantly about ethical technology, speculative fiction, and intentional community."
default_keywords: "blog, accessibility, technology, science fiction, fantasy"

# Collections
collections_dir: collections
collections:
    images:
        output: false

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-toc
  - jekyll-paginate

# Plugin: jekyll-toc
toc:
  min_level: 1
  max_level: 6
  ordered_list: true
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-
